import type {
  AuthenticatedMedusaRequest,
  MedusaResponse,
} from "@medusajs/framework/http"
import { z } from "@medusajs/framework/zod"
import {
  buildStudioVariantPlan,
  cleanStudioVariantProductId,
  loadStudioVariantProduct,
  studioVariantDraftProblem,
  studioVariantGraphExists,
} from "../../../../lib/studio-variants"

const PlanQuery = z.object({
  product_id: z.string().trim().min(3).max(160),
})

export const GET = async (
  req: AuthenticatedMedusaRequest,
  res: MedusaResponse
) => {
  const parsed = PlanQuery.safeParse(req.query)
  if (!parsed.success) {
    return res.status(400).json({ message: "A valid Studio product id is required." })
  }

  const productId = cleanStudioVariantProductId(parsed.data.product_id)
  if (!productId) {
    return res.status(400).json({ message: "A valid Studio product id is required." })
  }

  const product = await loadStudioVariantProduct(req, productId)
  const guard = studioVariantDraftProblem(product)
  if (guard) {
    return res.status(guard.status).json({ message: guard.message, code: guard.code })
  }

  const metadata = product!.metadata ?? {}
  const generated = metadata.coquette_studio_variants_generated === "true"
  const currentOptionCount = product!.options?.length ?? 0
  const currentVariantCount = product!.variants?.length ?? 0

  if (studioVariantGraphExists(product!)) {
    return res.status(200).json({
      state: generated ? "generated" : "blocked",
      ready: false,
      generated,
      blueprint_hash:
        typeof metadata.coquette_studio_variant_blueprint_hash === "string"
          ? metadata.coquette_studio_variant_blueprint_hash
          : null,
      option_count: currentOptionCount,
      variant_count: currentVariantCount,
      message: generated
        ? "The saved choice blueprint has already been built into a Medusa variant graph."
        : "This product already has an option or variant graph that was not generated by this guarded Studio workflow.",
    })
  }

  const { plan, problem } = buildStudioVariantPlan(product!)
  if (!plan) {
    return res.status(200).json({
      state: "incomplete",
      ready: false,
      generated: false,
      problem,
    })
  }

  return res.status(200).json({
    state: "ready",
    ready: true,
    generated: false,
    plan: {
      mode: plan.mode,
      options: plan.options,
      variants: plan.variants.map((variant) => ({ title: variant.title })),
      variant_count: plan.variant_count,
      blueprint_hash: plan.blueprint_hash,
    },
    updated_at: product!.updated_at || null,
  })
}
